apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  selector: #filtra todos os pods que estaram incorporados nesse service baseado no matchLabels
    app: goserver
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-port-goserver
      port: 8080
      targetPort: 8080